"""Command line entry point for QMT/XtQuant."""

from __future__ import annotations

import argparse
import json
import os
import sys
import threading
from dataclasses import asdict, is_dataclass
from importlib import resources
from typing import Any

from qmtcli.gateway import QMTConnection, QMTGateway

try:
    import numpy as _np
except ImportError:  # pragma: no cover - exercised only when numpy is absent
    _np = None
try:
    import pandas as _pd
except ImportError:  # pragma: no cover - exercised only when pandas is absent
    _pd = None


def _scrub(obj: Any) -> Any:
    """Recursively replace NaN/NaT/NA leaves with None so json.dumps emits valid JSON null.

    json's own encoder happily emits the non-standard ``NaN`` token for float('nan') and never
    calls ``default`` for it, so this has to run before the value reaches json.dumps.
    """
    if isinstance(obj, dict):
        return {key: _scrub(item) for key, item in obj.items()}
    if isinstance(obj, list):
        return [_scrub(item) for item in obj]
    if _pd is not None and (obj is _pd.NaT or obj is _pd.NA):
        return None
    if isinstance(obj, float) and obj != obj:  # NaN is the only float unequal to itself
        return None
    return obj


def _json_default(value: Any) -> Any:
    if _pd is not None and isinstance(value, _pd.DataFrame):
        if isinstance(value.index, _pd.RangeIndex):
            records = value.to_dict(orient="records")
        else:
            # Keep a non-trivial index (commonly a time index) as a plain column instead of
            # dropping it.
            records = value.reset_index().to_dict(orient="records")
        return _scrub(records)
    if _pd is not None and isinstance(value, _pd.Series):
        return _scrub(value.to_dict())
    if _pd is not None and isinstance(value, _pd.Timestamp):
        return value.isoformat()
    if _np is not None and isinstance(value, _np.ndarray):
        return value.tolist()
    if _np is not None and isinstance(value, _np.generic):
        return value.item()
    if is_dataclass(value):
        return asdict(value)
    if hasattr(value, "__dict__"):
        return value.__dict__
    if type(value).__module__.split(".")[0] == "xtquant":
        # xtpythonclient pyd objects (XtAccountInfo, ...) expose plain attributes but
        # have no __dict__; scrape the public, non-callable ones.
        return {
            name: attr
            for name in dir(value)
            if not name.startswith("_")
            for attr in [getattr(value, name, None)]
            if not callable(attr)
        }
    return str(value)


_print_lock = threading.Lock()


def _emit(obj: Any) -> None:
    """Thread-safe single-line JSON print used by the server loop and subscription callbacks."""
    with _print_lock:
        print(json.dumps(obj, ensure_ascii=False, default=_json_default), flush=True)


def _print_json(value: Any) -> None:
    print(json.dumps(value, ensure_ascii=False, default=_json_default, indent=2))


_XTDATA_FIELDS_CACHE: dict[str, Any] | None = None


def _load_xtdata_fields() -> dict[str, Any]:
    """Load the static xtdata field-name dictionaries generated by scripts/extract_doc_fields.py.

    Cached after the first successful load. Falls back to an empty catalog (rather than raising)
    if the generated JSON is missing or unreadable, so ``build_parser()`` never crashes just
    because ``fields`` lost its data file; ``fields`` dispatch reports a clear error instead.
    """
    global _XTDATA_FIELDS_CACHE
    if _XTDATA_FIELDS_CACHE is None:
        try:
            raw = resources.files("qmtcli").joinpath("xtdata_fields.json").read_text(encoding="utf-8")
            _XTDATA_FIELDS_CACHE = json.loads(raw)
        except (FileNotFoundError, OSError, json.JSONDecodeError):
            _XTDATA_FIELDS_CACHE = {}
    return _XTDATA_FIELDS_CACHE


def _dispatch_fields_command(kind: str | None) -> Any:
    catalog = _load_xtdata_fields()
    if not catalog:
        raise ValueError("fields catalog is unavailable; run scripts/extract_doc_fields.py")
    if not kind:
        return {name: entry["title"] for name, entry in catalog.items()}
    if kind not in catalog:
        raise ValueError(f"unknown fields kind: {kind}; choices: {sorted(catalog)}")
    return catalog[kind]["fields"]


AGENT_CAPABILITIES: dict[str, Any] = {
    "protocol": "qmtcli.agent.v1",
    "transports": ["cli", "rpc", "server"],
    "commands": [
        {
            "name": "status",
            "rpc_command": "status",
            "description": "Check whether xtquant is importable.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"path": "optional QMT root or userdata_mini path"},
        },
        {
            "name": "doctor",
            "rpc_command": "doctor",
            "description": "Return SDK/module/path diagnostics.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"path": "optional", "account": "optional"},
        },
        {
            "name": "data_call",
            "cli_command": "data-call",
            "description": "Call a public xtquant.xtdata method.",
            "requires_account": False,
            "danger": "escape_hatch",
            "inputs": {"method": "required", "args": "optional array", "kwargs": "optional object"},
        },
        {
            "name": "fields",
            "rpc_command": "fields",
            "description": (
                "Print static xtdata field-name reference dictionaries extracted from the doc "
                "appendix (tick, kline, balance, ...). Works fully offline; no QMT install needed."
            ),
            "requires_account": False,
            "danger": "safe",
            "inputs": {"kind": "optional; omit to list available kinds and titles"},
        },
        {
            "name": "download",
            "rpc_command": "download",
            "description": "Call an xtdata download_* function to populate the local QMT cache.",
            "requires_account": False,
            "danger": "downloads_data",
            "inputs": {
                "target": (
                    "required, one of history, financials, sectors, index-weight, cb, etf, "
                    "holidays, history-contracts"
                ),
                "symbols": "required for the history and financials targets",
            },
        },
        {
            "name": "calendar",
            "rpc_command": "calendar",
            "description": "Call xtdata.get_trading_calendar.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "market": "required, for example SH or SZ",
                "start": "optional start_time",
                "end": "optional end_time",
            },
        },
        {
            "name": "sector-list",
            "rpc_command": "sector_list",
            "description": "Call xtdata.get_sector_list.",
            "requires_account": False,
            "danger": "safe",
        },
        {
            "name": "sector-stocks",
            "rpc_command": "sector_stocks",
            "description": "Call xtdata.get_stock_list_in_sector.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"sector": "required sector name, for example 沪深A股"},
        },
        {
            "name": "full-tick",
            "rpc_command": "full_tick",
            "description": "Call xtdata.get_full_tick.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"symbols": "one or more symbols"},
        },
        {
            "name": "bars",
            "rpc_command": "bars",
            "description": "Call xtdata.get_market_data_ex.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "symbols": "one or more symbols",
                "fields": "optional field list",
                "period": "default 1d",
                "start": "optional start_time",
                "end": "optional end_time",
                "count": "default -1",
                "dividend_type": "default none",
                "fill_data": "default true; pass --no-fill-data to disable",
            },
        },
        {
            "name": "l2-quote",
            "rpc_command": "l2_quote",
            "description": "Call xtdata.get_l2_quote.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "symbol": "required single symbol",
                "fields": "optional field list",
                "start": "optional start_time",
                "end": "optional end_time",
                "count": "default -1",
            },
            "note": "requires Level-2 data permission; not covered by the public xtdata doc page",
        },
        {
            "name": "l2-order",
            "rpc_command": "l2_order",
            "description": "Call xtdata.get_l2_order.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "symbol": "required single symbol",
                "fields": "optional field list",
                "start": "optional start_time",
                "end": "optional end_time",
                "count": "default -1",
            },
            "note": "requires Level-2 data permission; not covered by the public xtdata doc page",
        },
        {
            "name": "l2-transaction",
            "rpc_command": "l2_transaction",
            "description": "Call xtdata.get_l2_transaction.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "symbol": "required single symbol",
                "fields": "optional field list",
                "start": "optional start_time",
                "end": "optional end_time",
                "count": "default -1",
            },
            "note": "requires Level-2 data permission; not covered by the public xtdata doc page",
        },
        {
            "name": "instrument-detail",
            "rpc_command": "instrument_detail",
            "description": "Call xtdata.get_instrument_detail.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"symbol": "required", "complete": "optional, default false"},
        },
        {
            "name": "instrument-type",
            "rpc_command": "instrument_type",
            "description": "Call xtdata.get_instrument_type.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"symbol": "required"},
        },
        {
            "name": "trading-dates",
            "rpc_command": "trading_dates",
            "description": "Call xtdata.get_trading_dates.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "market": "required, for example SH or SZ",
                "start": "optional start_time",
                "end": "optional end_time",
                "count": "default -1",
            },
        },
        {
            "name": "divid-factors",
            "rpc_command": "divid_factors",
            "description": "Call xtdata.get_divid_factors.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"symbol": "required", "start": "optional start_time", "end": "optional end_time"},
        },
        {
            "name": "holidays",
            "rpc_command": "holidays",
            "description": "Call xtdata.get_holidays.",
            "requires_account": False,
            "danger": "safe",
        },
        {
            "name": "period-list",
            "rpc_command": "period_list",
            "description": "Call xtdata.get_period_list.",
            "requires_account": False,
            "danger": "safe",
        },
        {
            "name": "ipo-info",
            "rpc_command": "ipo_info",
            "description": "Call xtdata.get_ipo_info.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"start": "optional start_time", "end": "optional end_time"},
        },
        {
            "name": "cb-info",
            "rpc_command": "cb_info",
            "description": "Call xtdata.get_cb_info.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"symbol": "required convertible bond code, for example 123001.SZ"},
        },
        {
            "name": "etf-info",
            "rpc_command": "etf_info",
            "description": "Call xtdata.get_etf_info.",
            "requires_account": False,
            "danger": "safe",
        },
        {
            "name": "index-weight",
            "rpc_command": "index_weight",
            "description": "Call xtdata.get_index_weight.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {"index_code": "required, for example 000300.SH"},
        },
        {
            "name": "financials",
            "rpc_command": "financials",
            "description": "Call xtdata.get_financial_data.",
            "requires_account": False,
            "danger": "safe",
            "inputs": {
                "symbols": "one or more symbols",
                "tables": "optional financial table list",
                "start": "optional start_time",
                "end": "optional end_time",
                "report_type": "default report_time",
            },
        },
        {
            "name": "asset",
            "description": "Query account asset.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "positions",
            "description": "Query account positions.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "orders",
            "description": "Query account orders.",
            "requires_account": True,
            "danger": "safe",
            "inputs": {"cancelable_only": "optional, default false; only return cancelable orders"},
        },
        {
            "name": "trades",
            "description": "Query account trades.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "position-statistics",
            "rpc_command": "position_statistics",
            "description": "Query position statistics via XtQuantTrader.query_position_statistics.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "credit-detail",
            "rpc_command": "credit_detail",
            "description": "Query credit account detail via XtQuantTrader.query_credit_detail.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "stk-compacts",
            "rpc_command": "stk_compacts",
            "description": "Query outstanding debt compacts via XtQuantTrader.query_stk_compacts.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "credit-subjects",
            "rpc_command": "credit_subjects",
            "description": "Query margin-trading subject list via XtQuantTrader.query_credit_subjects.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "credit-slo-code",
            "rpc_command": "credit_slo_code",
            "description": "Query lendable-securities codes via XtQuantTrader.query_credit_slo_code.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "credit-assure",
            "rpc_command": "credit_assure",
            "description": "Query collateral (assure) securities via XtQuantTrader.query_credit_assure.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "ipo-limit",
            "rpc_command": "ipo_limit",
            "description": "Query new-purchase (IPO) quota via XtQuantTrader.query_new_purchase_limit.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "com-fund",
            "rpc_command": "com_fund",
            "description": "Query ordinary-account fund info via XtQuantTrader.query_com_fund.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "com-position",
            "rpc_command": "com_position",
            "description": "Query ordinary-account positions via XtQuantTrader.query_com_position.",
            "requires_account": True,
            "danger": "safe",
        },
        {
            "name": "ipo-data",
            "rpc_command": "ipo_data",
            "description": "Query today's IPO data via XtQuantTrader.query_ipo_data.",
            "requires_account": False,
            "danger": "safe",
            "note": "connects to QMT session; no account id needed",
        },
        {
            "name": "account-infos",
            "rpc_command": "account_infos",
            "description": "Query connected account infos via XtQuantTrader.query_account_infos.",
            "requires_account": False,
            "danger": "safe",
            "note": "connects to QMT session; no account id needed",
        },
        {
            "name": "account-status",
            "rpc_command": "account_status",
            "description": "Query connected account status via XtQuantTrader.query_account_status.",
            "requires_account": False,
            "danger": "safe",
            "note": "connects to QMT session; no account id needed",
        },
        {
            "name": "buy",
            "description": "Submit a fixed-price stock buy order.",
            "requires_account": True,
            "danger": "places_order",
            "inputs": {"symbol": "required", "volume": "positive multiple of 100", "price": "positive"},
        },
        {
            "name": "sell",
            "description": "Submit a fixed-price stock sell order.",
            "requires_account": True,
            "danger": "places_order",
            "inputs": {"symbol": "required", "volume": "positive multiple of 100", "price": "positive"},
        },
        {
            "name": "cancel",
            "description": "Cancel an order by QMT order id.",
            "requires_account": True,
            "danger": "cancels_order",
            "inputs": {"order_id": "required"},
        },
        {
            "name": "trade_call",
            "cli_command": "trade-call",
            "description": "Call a public XtQuantTrader method.",
            "requires_account": True,
            "danger": "escape_hatch",
            "inputs": {
                "method": "required",
                "args": "optional array",
                "kwargs": "optional object",
                "with_account": "default true",
            },
        },
        {
            "name": "subscribe",
            "rpc_command": "subscribe",
            "description": "Subscribe to streaming quote pushes for one symbol via xtdata.subscribe_quote.",
            "requires_account": False,
            "danger": "safe",
            "transports": ["server"],
            "inputs": {"symbol": "required", "period": "default 1d", "count": "default 0"},
            "note": (
                "Only available in server mode. Streaming events interleave with responses on "
                "stdout; each event line carries an 'event' field instead of 'ok'."
            ),
        },
        {
            "name": "subscribe_whole",
            "rpc_command": "subscribe_whole",
            "description": (
                "Subscribe to streaming quote pushes for multiple symbols via "
                "xtdata.subscribe_whole_quote."
            ),
            "requires_account": False,
            "danger": "safe",
            "transports": ["server"],
            "inputs": {"symbols": "required array"},
            "note": (
                "Only available in server mode. Streaming events interleave with responses on "
                "stdout; each event line carries an 'event' field instead of 'ok'."
            ),
        },
        {
            "name": "unsubscribe",
            "rpc_command": "unsubscribe",
            "description": "Cancel a subscription via xtdata.unsubscribe_quote.",
            "requires_account": False,
            "danger": "safe",
            "transports": ["server"],
            "inputs": {"seq": "required, the subscription id returned by subscribe/subscribe_whole"},
            "note": "Only available in server mode.",
        },
    ],
}

AGENT_SCHEMA: dict[str, Any] = {
    "protocol": "qmtcli.agent.v1",
    "request": {
        "id": "optional string or number; echoed when present",
        "command": "required string",
        "path": "optional QMT root or userdata_mini path",
        "account": "required for account/trade commands",
        "account_type": "optional, default STOCK",
        "data_commands": (
            "Named data commands (calendar, bars, sector-stocks, ...) accept their CLI "
            "parameter names as JSON fields, with either dashes or underscores in the command "
            'name, e.g. {"command":"bars","symbols":["600519.SH"],"period":"1d"}.'
        ),
    },
    "response": {
        "ok": "boolean",
        "data": "present on success",
        "error": "present on failure",
        "id": "echoed when request id exists",
    },
    "server": {
        "transport": "stdin/stdout JSONL",
        "network": False,
        "line_contract": "one JSON request per input line, one JSON response per output line",
        "events": "subscription pushes appear as lines with an event field; responses have ok field",
    },
    "danger_levels": {
        "safe": "read-only or local diagnostics",
        "escape_hatch": "calls a public SDK method selected by the caller",
        "downloads_data": "downloads data into the local QMT cache",
        "places_order": "submits a broker order",
        "cancels_order": "cancels a broker order",
    },
}

AGENT_EXAMPLES: dict[str, Any] = {
    "status": {"command": "status"},
    "doctor": {"command": "doctor", "path": "D:\\DFZQxtqmt_client_real_win64\\userdata_mini"},
    "data_call": {
        "command": "data_call",
        "method": "get_stock_list_in_sector",
        "args": ["沪深A股"],
        "kwargs": {},
    },
    "calendar": {"command": "calendar", "market": "SH"},
    "bars": {"command": "bars", "symbols": ["600519.SH"], "period": "1d", "count": 10},
    "fields": {"command": "fields", "kind": "tick"},
    "download": {
        "command": "download",
        "target": "history",
        "symbols": ["600519.SH"],
        "period": "1d",
    },
    "subscribe": {"command": "subscribe", "symbol": "600519.SH", "period": "1d"},
    "credit_detail": {
        "command": "credit_detail",
        "path": "D:\\DFZQxtqmt_client_real_win64\\userdata_mini",
        "account": "ACCOUNT_ID",
        "account_type": "STOCK",
    },
    "ipo_data": {
        "command": "ipo_data",
        "path": "D:\\DFZQxtqmt_client_real_win64\\userdata_mini",
    },
    "buy": {
        "command": "buy",
        "path": "D:\\DFZQxtqmt_client_real_win64\\userdata_mini",
        "account": "ACCOUNT_ID",
        "account_type": "STOCK",
        "symbol": "600519.SH",
        "volume": 100,
        "price": 1500.0,
    },
}


def _agent_response(data: Any) -> dict[str, Any]:
    return {"ok": True, "data": data}


def _parser(description: str, **kwargs: Any) -> argparse.ArgumentParser:
    return argparse.ArgumentParser(
        description=description,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        **kwargs,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = _parser(
        "Local QMT/XtQuant command line bridge.\n"
        "All commands talk to the local broker QMT installation; qmtcli does not download QMT.",
    )
    parser.add_argument("--path", help="QMT install root or userdata_mini path")
    parser.add_argument("--account", help="QMT account id; required by trade/account commands")
    parser.add_argument("--account-type", default="STOCK", help="QMT account type, default: STOCK")
    parser.add_argument(
        "--xtdc-token",
        default=os.environ.get("QMTCLI_XTDC_TOKEN", ""),
        help=(
            "迅投投研 xtdatacenter token; when set, initializes standalone xtdc data mode before "
            "any command runs (experimental). Env fallback: QMTCLI_XTDC_TOKEN"
        ),
    )
    parser.add_argument(
        "--xtdc-port",
        type=int,
        default=58620,
        help="xtdatacenter local service port; default: 58620 (experimental, accepted but not yet wired)",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("capabilities", help="print agent-readable capability metadata")
    subparsers.add_parser("schema", help="print agent-readable RPC/server schema")
    subparsers.add_parser("examples", help="print built-in agent request examples")
    subparsers.add_parser("status", help="check whether xtquant is importable")
    subparsers.add_parser("doctor", help="show SDK/module/path diagnostics")
    subparsers.add_parser("asset", help="query stock asset for --account")
    subparsers.add_parser("positions", help="query positions for --account")
    orders = subparsers.add_parser("orders", help="query orders for --account")
    orders.add_argument(
        "--cancelable-only",
        action="store_true",
        help="only return cancelable orders",
    )
    subparsers.add_parser("trades", help="query trades for --account")
    subparsers.add_parser(
        "position-statistics",
        help="call XtQuantTrader.query_position_statistics for --account",
    )
    subparsers.add_parser(
        "credit-detail",
        help="call XtQuantTrader.query_credit_detail for --account",
    )
    subparsers.add_parser(
        "stk-compacts",
        help="call XtQuantTrader.query_stk_compacts for --account",
    )
    subparsers.add_parser(
        "credit-subjects",
        help="call XtQuantTrader.query_credit_subjects for --account",
    )
    subparsers.add_parser(
        "credit-slo-code",
        help="call XtQuantTrader.query_credit_slo_code for --account",
    )
    subparsers.add_parser(
        "credit-assure",
        help="call XtQuantTrader.query_credit_assure for --account",
    )
    subparsers.add_parser(
        "ipo-limit",
        help="call XtQuantTrader.query_new_purchase_limit for --account",
    )
    subparsers.add_parser(
        "com-fund",
        help="call XtQuantTrader.query_com_fund for --account",
    )
    subparsers.add_parser(
        "com-position",
        help="call XtQuantTrader.query_com_position for --account",
    )
    subparsers.add_parser(
        "ipo-data",
        help="call XtQuantTrader.query_ipo_data (no --account needed; connects to QMT session)",
    )
    subparsers.add_parser(
        "account-infos",
        help="call XtQuantTrader.query_account_infos (no --account needed; connects to QMT session)",
    )
    subparsers.add_parser(
        "account-status",
        help="call XtQuantTrader.query_account_status (no --account needed; connects to QMT session)",
    )
    calendar = subparsers.add_parser(
        "calendar",
        help="call xtdata.get_trading_calendar",
        description="Return trading calendar days for a market via xtdata.get_trading_calendar.",
    )
    calendar.add_argument("market", help="Market such as SH, SZ")
    calendar.add_argument("--start", default="", help="Start date YYYYMMDD; default: ''")
    calendar.add_argument("--end", default="", help="End date YYYYMMDD; default: ''")

    subparsers.add_parser("sector-list", help="call xtdata.get_sector_list")

    sector_stocks = subparsers.add_parser(
        "sector-stocks",
        help="call xtdata.get_stock_list_in_sector",
        description="Return stocks in an xtdata sector, for example: 沪深A股.",
    )
    sector_stocks.add_argument("sector", help="Sector name, for example: 沪深A股")

    full_tick = subparsers.add_parser(
        "full-tick",
        help="call xtdata.get_full_tick",
        description="Return latest full-tick data for one or more symbols.",
    )
    full_tick.add_argument("symbols", nargs="+", help="Symbols such as 600519.SH 000001.SZ")

    bars = subparsers.add_parser(
        "bars",
        help="call xtdata.get_market_data_ex",
        description="Return historical bars via xtdata.get_market_data_ex.",
    )
    bars.add_argument("symbols", nargs="+", help="Symbols such as 600519.SH")
    bars.add_argument("--fields", nargs="*", default=[], help="Field list; default: all fields")
    bars.add_argument("--period", default="1d", help="Period such as 1d, 1m, 5m; default: 1d")
    bars.add_argument("--start", default="", help="Start time; default: ''")
    bars.add_argument("--end", default="", help="End time; default: ''")
    bars.add_argument("--count", default=-1, type=int, help="Bar count; default: -1")
    bars.add_argument(
        "--dividend-type",
        default="none",
        help="Dividend type: none, front, back, front_ratio, back_ratio; default: none",
    )
    bars.add_argument(
        "--no-fill-data",
        action="store_true",
        help="Disable forward-filling of missing bars (fill_data=False)",
    )

    l2_quote = subparsers.add_parser(
        "l2-quote",
        help="call xtdata.get_l2_quote",
        description=(
            "Return Level-2 quote snapshots for a single symbol via xtdata.get_l2_quote.\n"
            "Requires Level-2 data permission; not covered by the public xtdata doc page."
        ),
    )
    l2_quote.add_argument("symbol", help="Symbol such as 600519.SH")
    l2_quote.add_argument("--fields", nargs="*", default=[], help="Field list; default: all fields")
    l2_quote.add_argument("--start", default="", help="Start time; default: ''")
    l2_quote.add_argument("--end", default="", help="End time; default: ''")
    l2_quote.add_argument("--count", default=-1, type=int, help="Count; default: -1")

    l2_order = subparsers.add_parser(
        "l2-order",
        help="call xtdata.get_l2_order",
        description=(
            "Return Level-2 order queue data for a single symbol via xtdata.get_l2_order.\n"
            "Requires Level-2 data permission; not covered by the public xtdata doc page."
        ),
    )
    l2_order.add_argument("symbol", help="Symbol such as 600519.SH")
    l2_order.add_argument("--fields", nargs="*", default=[], help="Field list; default: all fields")
    l2_order.add_argument("--start", default="", help="Start time; default: ''")
    l2_order.add_argument("--end", default="", help="End time; default: ''")
    l2_order.add_argument("--count", default=-1, type=int, help="Count; default: -1")

    l2_transaction = subparsers.add_parser(
        "l2-transaction",
        help="call xtdata.get_l2_transaction",
        description=(
            "Return Level-2 transaction data for a single symbol via xtdata.get_l2_transaction.\n"
            "Requires Level-2 data permission; not covered by the public xtdata doc page."
        ),
    )
    l2_transaction.add_argument("symbol", help="Symbol such as 600519.SH")
    l2_transaction.add_argument("--fields", nargs="*", default=[], help="Field list; default: all fields")
    l2_transaction.add_argument("--start", default="", help="Start time; default: ''")
    l2_transaction.add_argument("--end", default="", help="End time; default: ''")
    l2_transaction.add_argument("--count", default=-1, type=int, help="Count; default: -1")

    instrument_detail = subparsers.add_parser(
        "instrument-detail",
        help="call xtdata.get_instrument_detail",
    )
    instrument_detail.add_argument("symbol", help="Symbol such as 600519.SH")
    instrument_detail.add_argument(
        "--complete",
        action="store_true",
        help="Return the complete instrument detail field set",
    )

    instrument_type = subparsers.add_parser(
        "instrument-type",
        help="call xtdata.get_instrument_type",
    )
    instrument_type.add_argument("symbol", help="Symbol such as 600519.SH")

    trading_dates = subparsers.add_parser(
        "trading-dates",
        help="call xtdata.get_trading_dates",
    )
    trading_dates.add_argument("market", help="Market such as SH, SZ")
    trading_dates.add_argument("--start", default="", help="Start date YYYYMMDD; default: ''")
    trading_dates.add_argument("--end", default="", help="End date YYYYMMDD; default: ''")
    trading_dates.add_argument("--count", default=-1, type=int, help="Date count; default: -1")

    divid_factors = subparsers.add_parser(
        "divid-factors",
        help="call xtdata.get_divid_factors",
    )
    divid_factors.add_argument("symbol", help="Symbol such as 600519.SH")
    divid_factors.add_argument("--start", default="", help="Start time; default: ''")
    divid_factors.add_argument("--end", default="", help="End time; default: ''")

    subparsers.add_parser("holidays", help="call xtdata.get_holidays")
    subparsers.add_parser("period-list", help="call xtdata.get_period_list")

    ipo_info = subparsers.add_parser("ipo-info", help="call xtdata.get_ipo_info")
    ipo_info.add_argument("--start", default="", help="Start time; default: ''")
    ipo_info.add_argument("--end", default="", help="End time; default: ''")

    cb_info = subparsers.add_parser("cb-info", help="call xtdata.get_cb_info")
    cb_info.add_argument("symbol", help="Convertible bond code such as 123001.SZ")

    subparsers.add_parser("etf-info", help="call xtdata.get_etf_info")

    index_weight = subparsers.add_parser("index-weight", help="call xtdata.get_index_weight")
    index_weight.add_argument("index_code", help="Index code such as 000300.SH")

    financials = subparsers.add_parser(
        "financials",
        help="call xtdata.get_financial_data",
    )
    financials.add_argument("symbols", nargs="+", help="Symbols such as 600519.SH")
    financials.add_argument(
        "--tables",
        nargs="*",
        default=[],
        help="Financial table names such as Balance, Income; default: all tables",
    )
    financials.add_argument("--start", default="", help="Start time; default: ''")
    financials.add_argument("--end", default="", help="End time; default: ''")
    financials.add_argument(
        "--report-type",
        default="report_time",
        help="report_time or announce_time; default: report_time",
    )

    download = subparsers.add_parser(
        "download",
        help="call an xtdata download_* function to populate the local QMT cache",
        description=(
            "Download data into the local QMT cache via xtdata download_* functions.\n"
            "target: history, financials, sectors, index-weight, cb, etf, holidays, "
            "history-contracts.\n"
            "symbols are required for the history and financials targets.\n\n"
            "Example:\n"
            "  qmtcli download history 600519.SH --period 1d"
        ),
    )
    download.add_argument(
        "target",
        choices=[
            "history",
            "financials",
            "sectors",
            "index-weight",
            "cb",
            "etf",
            "holidays",
            "history-contracts",
        ],
        help="What to download",
    )
    download.add_argument(
        "symbols",
        nargs="*",
        help="Symbols; required for the history and financials targets",
    )
    download.add_argument("--period", default="1d", help="Period for the history target; default: 1d")
    download.add_argument("--start", default="", help="Start time; default: ''")
    download.add_argument("--end", default="", help="End time; default: ''")
    download.add_argument(
        "--incrementally",
        action="store_true",
        help="For the history target, only download data since the last local update",
    )
    download.add_argument(
        "--tables",
        nargs="*",
        default=[],
        help="Financial table names for the financials target; default: all tables",
    )

    fields_kinds = sorted(_load_xtdata_fields()) or None
    fields = subparsers.add_parser(
        "fields",
        help="print static xtdata field-name dictionaries from the doc appendix (offline)",
        description=(
            "Print static xtdata field-name reference dictionaries extracted from the doc "
            "appendix (tick, kline, balance, ...).\n"
            "Works fully offline; does not require a QMT install.\n"
            "With no kind argument, lists the available kinds and their titles.\n\n"
            "Example:\n"
            "  qmtcli fields tick"
        ),
    )
    fields.add_argument(
        "kind",
        nargs="?",
        default=None,
        choices=fields_kinds,
        help="Field dictionary kind, for example tick, kline, balance; omit to list all kinds",
    )

    data_call = subparsers.add_parser(
        "data-call",
        help="call an arbitrary public xtquant.xtdata method",
        description=(
            "Call an arbitrary public xtquant.xtdata method.\n"
            "Private methods beginning with '_' are blocked.\n\n"
            "Example:\n"
            "  qmtcli data-call get_stock_list_in_sector --args '[\"沪深A股\"]'"
        ),
    )
    data_call.add_argument("method", help="Public xtdata method name")
    data_call.add_argument("--args", default="[]", help="JSON positional args array; default: []")
    data_call.add_argument("--kwargs", default="{}", help="JSON keyword args object; default: {}")

    trade_call = subparsers.add_parser(
        "trade-call",
        help="call an arbitrary public XtQuantTrader method",
        description=(
            "Call an arbitrary public XtQuantTrader method after connecting --account.\n"
            "By default the StockAccount object is prepended to args; pass --no-account to skip it.\n"
            "Private methods beginning with '_' are blocked."
        ),
    )
    trade_call.add_argument("method", help="Public XtQuantTrader method name")
    trade_call.add_argument("--args", default="[]", help="JSON positional args array; default: []")
    trade_call.add_argument("--kwargs", default="{}", help="JSON keyword args object; default: {}")
    trade_call.add_argument("--no-account", action="store_true", help="Do not prepend StockAccount")

    buy = subparsers.add_parser("buy", help="submit a fixed-price stock buy order")
    buy.add_argument("symbol", help="Symbol such as 600519.SH")
    buy.add_argument("volume", type=int, help="A-share volume; must be a positive multiple of 100")
    buy.add_argument("price", type=float, help="Limit price; must be positive")

    sell = subparsers.add_parser("sell", help="submit a fixed-price stock sell order")
    sell.add_argument("symbol", help="Symbol such as 600519.SH")
    sell.add_argument("volume", type=int, help="A-share volume; must be a positive multiple of 100")
    sell.add_argument("price", type=float, help="Limit price; must be positive")

    cancel = subparsers.add_parser("cancel", help="cancel an order by QMT order id")
    cancel.add_argument("order_id", help="QMT order id")

    subparsers.add_parser(
        "rpc",
        help="handle one JSON request from stdin and print one JSON response",
        description=(
            "Read one JSON request from stdin and write one JSON response.\n"
            "Supported commands include status, doctor, data_call, fields, every named data\n"
            "command (calendar, bars, sector-stocks, download, ...), asset, positions, orders,\n"
            "trades, the named trader queries (credit-detail, ipo-data, ...), buy, sell, cancel,\n"
            "and trade_call. subscribe/subscribe_whole/unsubscribe are rejected here; they\n"
            "require server mode."
        ),
    )
    subparsers.add_parser(
        "server",
        help="run a stdin/stdout JSONL request loop",
        description=(
            "Read newline-delimited JSON requests from stdin and print one JSON response per line.\n"
            "This is a local automation loop, not a TCP server.\n"
            "subscribe/subscribe_whole/unsubscribe are only available here; quote pushes print as\n"
            "extra JSONL lines with an 'event' field, interleaved with normal responses."
        ),
    )
    return parser


def _connect(args: argparse.Namespace) -> QMTGateway:
    account_optional = getattr(args, "command", None) in ACCOUNT_OPTIONAL_COMMANDS
    if not args.account and not account_optional:
        raise SystemExit("--account is required for this command")
    gateway = QMTGateway(QMTConnection(args.path or "", args.account or "", args.account_type))
    gateway.connect(subscribe=not account_optional)
    return gateway


def main(argv: list[str] | None = None) -> int:
    # Windows defaults stdout to the ANSI code page (GBK on zh-CN); JSON output is UTF-8.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    args = build_parser().parse_args(argv)
    try:
        return _run_command(args)
    except Exception as exc:  # noqa: BLE001 - CLI boundary must report arbitrary failures cleanly.
        _print_json({"ok": False, "error": str(exc)})
        return 1


def _run_command(args: argparse.Namespace) -> int:
    if getattr(args, "xtdc_token", ""):
        QMTGateway.init_xtdc(args.xtdc_token, args.xtdc_port)
    if args.command == "rpc":
        return _rpc()
    if args.command == "server":
        return _server()
    if args.command == "capabilities":
        _print_json(_agent_response(AGENT_CAPABILITIES))
        return 0
    if args.command == "schema":
        _print_json(_agent_response(AGENT_SCHEMA))
        return 0
    if args.command == "examples":
        _print_json(_agent_response(AGENT_EXAMPLES))
        return 0
    if args.command == "status":
        _print_json({"xtquant": QMTGateway.is_available(args.path)})
        return 0
    if args.command == "doctor":
        _print_json(QMTGateway.sdk_diagnostics(args.path, args.account))
        return 0
    if args.command == "fields":
        _print_json(_dispatch_fields_command(args.kind))
        return 0
    if args.command in {
        "calendar",
        "sector-list",
        "sector-stocks",
        "full-tick",
        "bars",
        "l2-quote",
        "l2-order",
        "l2-transaction",
        "data-call",
        "instrument-detail",
        "instrument-type",
        "trading-dates",
        "divid-factors",
        "holidays",
        "period-list",
        "ipo-info",
        "cb-info",
        "etf-info",
        "index-weight",
        "financials",
        "download",
    }:
        _print_json(_handle_data_command(args))
        return 0

    gateway = _connect(args)
    if args.command == "asset":
        _print_json(gateway.query_asset())
    elif args.command == "positions":
        _print_json(gateway.query_positions())
    elif args.command == "orders":
        _print_json(gateway.query_orders(cancelable_only=args.cancelable_only))
    elif args.command == "trades":
        _print_json(gateway.query_trades())
    elif args.command in TRADE_QUERY_COMMANDS:
        spec = TRADE_QUERY_COMMANDS[args.command]
        _print_json(gateway.call_trader(spec["method"], with_account=spec["with_account"]))
    elif args.command == "buy":
        _print_json(gateway.submit_order(args.symbol, "BUY", args.volume, args.price))
    elif args.command == "sell":
        _print_json(gateway.submit_order(args.symbol, "SELL", args.volume, args.price))
    elif args.command == "cancel":
        _print_json(gateway.cancel_order(args.order_id))
    elif args.command == "trade-call":
        _print_json(
            gateway.call_trader(
                args.method,
                *json.loads(args.args),
                with_account=not args.no_account,
                **json.loads(args.kwargs),
            )
        )
    return 0


DATA_COMMAND_NAMES = {
    "calendar",
    "sector-list",
    "sector-stocks",
    "full-tick",
    "bars",
    "l2-quote",
    "l2-order",
    "l2-transaction",
    "instrument-detail",
    "instrument-type",
    "trading-dates",
    "divid-factors",
    "holidays",
    "period-list",
    "ipo-info",
    "cb-info",
    "etf-info",
    "index-weight",
    "financials",
    "download",
}

# The three account-less trader queries: they still need a connected QMT session (path/session_id)
# but the underlying XtQuantTrader method takes no account argument, so --account is optional and
# gateway.connect() is asked to skip trader.subscribe(account).
ACCOUNT_OPTIONAL_COMMANDS = {"ipo-data", "account-infos", "account-status"}

# Named read-only XtQuantTrader queries that map 1:1 onto call_trader(method, with_account=...)
# with no extra CLI arguments beyond the shared --account/--path/--account-type.
TRADE_QUERY_COMMANDS: dict[str, dict[str, Any]] = {
    "position-statistics": {"method": "query_position_statistics", "with_account": True},
    "credit-detail": {"method": "query_credit_detail", "with_account": True},
    "stk-compacts": {"method": "query_stk_compacts", "with_account": True},
    "credit-subjects": {"method": "query_credit_subjects", "with_account": True},
    "credit-slo-code": {"method": "query_credit_slo_code", "with_account": True},
    "credit-assure": {"method": "query_credit_assure", "with_account": True},
    "ipo-limit": {"method": "query_new_purchase_limit", "with_account": True},
    "com-fund": {"method": "query_com_fund", "with_account": True},
    "com-position": {"method": "query_com_position", "with_account": True},
    "ipo-data": {"method": "query_ipo_data", "with_account": False},
    "account-infos": {"method": "query_account_infos", "with_account": False},
    "account-status": {"method": "query_account_status", "with_account": False},
}


def _handle_data_command(args: argparse.Namespace) -> Any:
    # download's symbols requirement depends on --target and argparse's nargs="*" cannot express
    # that, so the CLI keeps its own SystemExit here; _dispatch_download_command raises ValueError
    # for the same condition when reached directly over rpc/server.
    if args.command == "download" and args.target in {"history", "financials"} and not args.symbols:
        raise SystemExit(f"download {args.target} requires one or more symbols")
    return _dispatch_data_command(args.command, vars(args))


def _dispatch_data_command(command: str, params: dict[str, Any]) -> Any:
    """Shared CLI/RPC data-command dispatch.

    ``params`` uses argparse dest names (market, symbol, symbols, fields, period, start, end,
    count, dividend_type, no_fill_data/fill_data, complete, tables, report_type, index_code,
    target, incrementally) so the same dict shape works whether it comes from ``vars(args)`` or a
    raw RPC/server request.
    """
    if command == "calendar":
        market = params.get("market")
        if not market:
            raise ValueError("calendar requires market")
        return QMTGateway.call_data(
            "get_trading_calendar",
            market,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
        )
    if command == "sector-list":
        return QMTGateway.call_data("get_sector_list")
    if command == "sector-stocks":
        sector = params.get("sector")
        if not sector:
            raise ValueError("sector-stocks requires sector")
        return QMTGateway.call_data("get_stock_list_in_sector", sector)
    if command == "full-tick":
        symbols = params.get("symbols")
        if not symbols:
            raise ValueError("full-tick requires symbols")
        return QMTGateway.call_data("get_full_tick", symbols)
    if command == "bars":
        symbols = params.get("symbols")
        if not symbols:
            raise ValueError("bars requires symbols")
        fill_data = params.get("fill_data", not params.get("no_fill_data", False))
        return QMTGateway.call_data(
            "get_market_data_ex",
            params.get("fields", []),
            symbols,
            period=params.get("period", "1d"),
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            count=params.get("count", -1),
            dividend_type=params.get("dividend_type", "none"),
            fill_data=fill_data,
        )
    if command == "l2-quote":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("l2-quote requires symbol")
        return QMTGateway.call_data(
            "get_l2_quote",
            params.get("fields", []),
            symbol,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            count=params.get("count", -1),
        )
    if command == "l2-order":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("l2-order requires symbol")
        return QMTGateway.call_data(
            "get_l2_order",
            params.get("fields", []),
            symbol,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            count=params.get("count", -1),
        )
    if command == "l2-transaction":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("l2-transaction requires symbol")
        return QMTGateway.call_data(
            "get_l2_transaction",
            params.get("fields", []),
            symbol,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            count=params.get("count", -1),
        )
    if command == "instrument-detail":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("instrument-detail requires symbol")
        return QMTGateway.call_data("get_instrument_detail", symbol, params.get("complete", False))
    if command == "instrument-type":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("instrument-type requires symbol")
        return QMTGateway.call_data("get_instrument_type", symbol)
    if command == "trading-dates":
        market = params.get("market")
        if not market:
            raise ValueError("trading-dates requires market")
        return QMTGateway.call_data(
            "get_trading_dates",
            market,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            count=params.get("count", -1),
        )
    if command == "divid-factors":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("divid-factors requires symbol")
        return QMTGateway.call_data(
            "get_divid_factors",
            symbol,
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
        )
    if command == "holidays":
        return QMTGateway.call_data("get_holidays")
    if command == "period-list":
        return QMTGateway.call_data("get_period_list")
    if command == "ipo-info":
        return QMTGateway.call_data(
            "get_ipo_info", start_time=params.get("start", ""), end_time=params.get("end", "")
        )
    if command == "cb-info":
        symbol = params.get("symbol")
        if not symbol:
            raise ValueError("cb-info requires symbol")
        return QMTGateway.call_data("get_cb_info", symbol)
    if command == "etf-info":
        return QMTGateway.call_data("get_etf_info")
    if command == "index-weight":
        index_code = params.get("index_code")
        if not index_code:
            raise ValueError("index-weight requires index_code")
        return QMTGateway.call_data("get_index_weight", index_code)
    if command == "financials":
        symbols = params.get("symbols")
        if not symbols:
            raise ValueError("financials requires symbols")
        return QMTGateway.call_data(
            "get_financial_data",
            symbols,
            table_list=params.get("tables", []),
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            report_type=params.get("report_type", "report_time"),
        )
    if command == "data-call":
        return QMTGateway.call_data(
            params["method"],
            *json.loads(params.get("args", "[]")),
            **json.loads(params.get("kwargs", "{}")),
        )
    if command == "download":
        return _dispatch_download_command(params)
    raise ValueError(f"unknown data command: {command}")


def _dispatch_download_command(params: dict[str, Any]) -> Any:
    target = params.get("target")
    if not target:
        raise ValueError("download requires target")
    symbols = params.get("symbols") or []
    if target == "history":
        if not symbols:
            raise ValueError("download requires symbols")
        QMTGateway.call_data(
            "download_history_data2",
            symbols,
            params.get("period", "1d"),
            start_time=params.get("start", ""),
            end_time=params.get("end", ""),
            incrementally=True if params.get("incrementally") else None,
        )
    elif target == "financials":
        if not symbols:
            raise ValueError("download requires symbols")
        QMTGateway.call_data("download_financial_data", symbols, table_list=params.get("tables", []))
    elif target == "sectors":
        QMTGateway.call_data("download_sector_data")
    elif target == "index-weight":
        QMTGateway.call_data("download_index_weight")
    elif target == "cb":
        QMTGateway.call_data("download_cb_data")
    elif target == "etf":
        QMTGateway.call_data("download_etf_info")
    elif target == "holidays":
        QMTGateway.call_data("download_holiday_data")
    elif target == "history-contracts":
        QMTGateway.call_data("download_history_contracts")
    else:
        raise ValueError(f"unknown download target: {target}")
    return {"ok": True, "downloaded": target, "symbols": symbols}


def _handle_rpc_request(request: dict[str, Any], allow_subscribe: bool = False) -> dict[str, Any]:
    request_id = request.get("id")
    try:
        data = _handle_rpc_data(request, allow_subscribe)
    except Exception as exc:  # noqa: BLE001 - JSON RPC boundary must report arbitrary failures.
        response = {"ok": False, "error": str(exc)}
    else:
        response = {"ok": True, "data": data}
    if request_id is not None:
        response["id"] = request_id
    return response


def _handle_rpc_data(request: dict[str, Any], allow_subscribe: bool = False) -> Any:
    command = request.get("command")
    if command == "capabilities":
        return AGENT_CAPABILITIES
    if command == "schema":
        return AGENT_SCHEMA
    if command == "examples":
        return AGENT_EXAMPLES
    if command == "status":
        return {"xtquant": QMTGateway.is_available(request.get("path"))}
    if command == "doctor":
        return QMTGateway.sdk_diagnostics(request.get("path"), request.get("account"))
    if command == "data_call":
        return QMTGateway.call_data(
            request["method"],
            *request.get("args", []),
            **request.get("kwargs", {}),
        )
    if command == "fields":
        return _dispatch_fields_command(request.get("kind"))
    if isinstance(command, str) and command.replace("_", "-") in DATA_COMMAND_NAMES:
        return _dispatch_data_command(command.replace("_", "-"), request)
    if command in {"subscribe", "subscribe_whole", "unsubscribe"}:
        if not allow_subscribe:
            raise ValueError("subscribe commands require server mode")
        return _dispatch_subscribe_command(command, request)
    if isinstance(command, str) and command.replace("_", "-") in TRADE_QUERY_COMMANDS:
        return _dispatch_trade_query_command(command.replace("_", "-"), request)

    account_commands = {
        "asset",
        "positions",
        "orders",
        "trades",
        "buy",
        "sell",
        "cancel",
        "trade_call",
    }
    if command not in account_commands:
        raise ValueError(f"unknown command: {command}")

    gateway = QMTGateway(
        QMTConnection(
            request.get("path", ""),
            request.get("account", ""),
            request.get("account_type", "STOCK"),
        )
    )
    gateway.connect()
    if command == "asset":
        return gateway.query_asset()
    if command == "positions":
        return gateway.query_positions()
    if command == "orders":
        return gateway.query_orders(cancelable_only=request.get("cancelable_only", False))
    if command == "trades":
        return gateway.query_trades()
    if command == "buy":
        return gateway.submit_order(request["symbol"], "BUY", request["volume"], request["price"])
    if command == "sell":
        return gateway.submit_order(request["symbol"], "SELL", request["volume"], request["price"])
    if command == "cancel":
        return gateway.cancel_order(request["order_id"])
    if command == "trade_call":
        return gateway.call_trader(
            request["method"],
            *request.get("args", []),
            with_account=request.get("with_account", True),
            **request.get("kwargs", {}),
        )


def _dispatch_trade_query_command(command: str, request: dict[str, Any]) -> Any:
    """Shared CLI/RPC dispatch for the named read-only XtQuantTrader queries in TRADE_QUERY_COMMANDS."""
    spec = TRADE_QUERY_COMMANDS[command]
    account_optional = command in ACCOUNT_OPTIONAL_COMMANDS
    gateway = QMTGateway(
        QMTConnection(
            request.get("path", ""),
            request.get("account", ""),
            request.get("account_type", "STOCK"),
        )
    )
    gateway.connect(subscribe=not account_optional)
    return gateway.call_trader(spec["method"], with_account=spec["with_account"])


def _dispatch_subscribe_command(command: str, request: dict[str, Any]) -> Any:
    if command == "subscribe":
        symbol = request.get("symbol")
        if not symbol:
            raise ValueError("subscribe requires symbol")
        period = request.get("period", "1d")
        count = request.get("count", 0)
        # seq is only known after call_data() returns, but the xtquant callback can fire on its
        # own thread before that assignment happens; cb reads seq_holder lazily so a (rare) early
        # event reports seq: None instead of raising. This small race is considered acceptable.
        seq_holder: dict[str, Any] = {}

        def cb(datas: Any) -> None:
            _emit({"event": "quote", "seq": seq_holder.get("seq"), "symbol": symbol, "data": datas})

        seq = QMTGateway.call_data("subscribe_quote", symbol, period=period, count=count, callback=cb)
        seq_holder["seq"] = seq
        return {"seq": seq}
    if command == "subscribe_whole":
        symbols = request.get("symbols")
        if not symbols:
            raise ValueError("subscribe_whole requires symbols")
        seq_holder = {}

        def cb(datas: Any) -> None:
            _emit(
                {
                    "event": "whole_quote",
                    "seq": seq_holder.get("seq"),
                    "symbols": symbols,
                    "data": datas,
                }
            )

        seq = QMTGateway.call_data("subscribe_whole_quote", symbols, callback=cb)
        seq_holder["seq"] = seq
        return {"seq": seq}
    if command == "unsubscribe":
        seq = request.get("seq")
        if seq is None:
            raise ValueError("unsubscribe requires seq")
        QMTGateway.call_data("unsubscribe_quote", seq)
        return {"unsubscribed": seq}
    raise ValueError(f"unknown command: {command}")


def _rpc() -> int:
    request = json.loads((sys.stdin.read() or "{}").lstrip("\ufeff"))
    print(json.dumps(_handle_rpc_request(request), ensure_ascii=False, default=_json_default, indent=2))
    return 0


def _server() -> int:
    for line in sys.stdin:
        line = line.strip().lstrip("\ufeff")
        if not line:
            continue
        response = _handle_rpc_request(json.loads(line), allow_subscribe=True)
        _emit(response)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
